apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-exam-app
  labels:
    app: cloud-exam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-exam-app
  template:
    metadata:
      labels:
        app: cloud-exam-app
    spec:
      containers:
        - name: student-scores
          image: mkennyro/expressapp
          ports:
            - containerPort: 3000
